"""add engagement actions

Revision ID: c77c5059fff2
Revises: 3467de398a47
Create Date: 2026-02-20 19:59:11.546431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77c5059fff2'
down_revision: Union[str, Sequence[str], None] = '3467de398a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('target_handle', sa.String(length=120), nullable=True),
    sa.Column('target_caption', sa.Text(), nullable=True),
    sa.Column('action_type', sa.Enum('comment', 'like', 'follow', name='engagementactiontype'), nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'executed', 'skipped', 'failed', name='engagementstatus'), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'action_type', 'target_url', name='uq_engagement_actions_target')
    )
    op.alter_column('post_drafts', 'broll_dir',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_drafts', 'broll_dir',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('engagement_actions')
    # ### end Alembic commands ###
